# Generated by Django 6.0.7 on 2026-09-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_mocktest_mocktestattempt_and_more'),
    ]

    operations = [
        # E'TIBOR: `AlterUniqueTogether` mocktestsection'ning `mock_test`/`quiz`
        # maydonlarini OLIB TASHLASHDAN OLDIN kelishi shart — aks holda SQLite
        # jadvalni qayta qurishda (`RemoveField`) hali state'da turgan
        # `unique_together`dagi maydonni topa olmay `FieldDoesNotExist` beradi
        # (Django autodetector'ning standart tartibi bu yerda noto'g'ri edi).
        migrations.AlterUniqueTogether(
            name='mocktestsection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mocktestsection',
            name='mock_test',
        ),
        migrations.RemoveField(
            model_name='mocktestattempt',
            name='mock_test',
        ),
        migrations.RemoveField(
            model_name='mocktestattempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='mock_test_attempt',
        ),
        migrations.RemoveField(
            model_name='mocktestsection',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='MockTest',
        ),
        migrations.DeleteModel(
            name='MockTestAttempt',
        ),
        migrations.DeleteModel(
            name='MockTestSection',
        ),
    ]
