# Generated by Django 6.0.7 on 2026-09-19 12:06

from django.db import migrations, models


def backfill_earned_points(apps, schema_editor):
    AnswerResponse = apps.get_model('quizzes', 'AnswerResponse')
    for answer in AnswerResponse.objects.filter(is_correct=True).select_related('question'):
        answer.earned_points = answer.question.points
        answer.save(update_fields=['earned_points'])


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_remove_mocktestsection_mock_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerresponse',
            name='answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerresponse',
            name='earned_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answerresponse',
            name='given_display',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_key',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', "Bitta to'g'ri javob"), ('multiple', "Bir nechta to'g'ri javob"), ('true_false', "To'g'ri / noto'g'ri"), ('numeric', 'Son kiritish'), ('text', 'Matn kiritish'), ('matching', 'Moslashtirish'), ('ordering', 'Tartibga solish'), ('fill_blank', "Bo'sh joyni to'ldirish")], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.RunPython(backfill_earned_points, migrations.RunPython.noop),
    ]
