# Generated by Django 6.0.7 on 2026-09-19 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_author_subject(apps, schema_editor):
    Quiz = apps.get_model('quizzes', 'Quiz')
    for quiz in Quiz.objects.filter(course__isnull=False).select_related('course'):
        quiz.author_id = quiz.course.teacher_id
        quiz.subject = quiz.course.subject
        quiz.save(update_fields=['author', 'subject'])


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_lesson_title'),
        ('quizzes', '0006_question_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Matematika'), ('physics', 'Fizika'), ('astronomy', 'Astronomiya'), ('chemistry', 'Kimyo'), ('biology', 'Biologiya'), ('ecology', 'Ekologiya'), ('computer_science', 'Informatika'), ('history', 'Tarix'), ('geography', 'Geografiya'), ('civics', 'Huquq asoslari'), ('economics', 'Iqtisodiyot asoslari'), ('literature', 'Ona tili va adabiyot'), ('music', 'Musiqa'), ('art', "Tasviriy san'at"), ('physical_education', 'Jismoniy tarbiya'), ('technology', 'Texnologiya'), ('chess', 'Shaxmat'), ('english', 'Ingliz tili'), ('russian', 'Rus tili'), ('turkish', 'Turk tili'), ('german', 'Nemis tili'), ('french', 'Fransuz tili'), ('arabic', 'Arab tili'), ('chinese', 'Xitoy tili'), ('korean', 'Koreys tili'), ('japanese', 'Yapon tili'), ('other', 'Boshqa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lessons.course'),
        ),
        migrations.RunPython(backfill_author_subject, migrations.RunPython.noop),
    ]
