# Generated by Django 6.0.7 on 2026-09-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quiz_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('published', "E'lon qilingan")], db_index=True, default='published', max_length=10),
        ),
    ]
