# Generated by Django 6.0.7 on 2026-10-08 06:54

import apps.core.uploads
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_lesson_title'),
        ('quizzes', '0010_question_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiQuizJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, choices=[('math', 'Matematika'), ('physics', 'Fizika'), ('astronomy', 'Astronomiya'), ('chemistry', 'Kimyo'), ('biology', 'Biologiya'), ('ecology', 'Ekologiya'), ('computer_science', 'Informatika'), ('history', 'Tarix'), ('geography', 'Geografiya'), ('civics', 'Huquq asoslari'), ('economics', 'Iqtisodiyot asoslari'), ('literature', 'Ona tili va adabiyot'), ('music', 'Musiqa'), ('art', "Tasviriy san'at"), ('physical_education', 'Jismoniy tarbiya'), ('technology', 'Texnologiya'), ('chess', 'Shaxmat'), ('english', 'Ingliz tili'), ('russian', 'Rus tili'), ('turkish', 'Turk tili'), ('german', 'Nemis tili'), ('french', 'Fransuz tili'), ('arabic', 'Arab tili'), ('chinese', 'Xitoy tili'), ('korean', 'Koreys tili'), ('japanese', 'Yapon tili'), ('other', 'Boshqa')], max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('standard', models.CharField(choices=[('uzbmb', 'Milliy sertifikat (UZBMB)'), ('ielts', 'IELTS Academic'), ('sat', 'Digital SAT')], max_length=10)),
                ('question_count', models.PositiveIntegerField(default=20)),
                ('source_file', models.FileField(blank=True, null=True, upload_to=apps.core.uploads.ai_quiz_source_path)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Navbatda'), ('processing', 'Material tahlil qilinmoqda'), ('generating', 'Savollar yaratilmoqda'), ('done', 'Tayyor'), ('failed', 'Xato')], db_index=True, default='queued', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('tc_document_id', models.CharField(blank=True, max_length=64)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.course')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quizzes.quiz')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quiz_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
