# Generated by Django 6.0.7 on 2026-10-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_ai_quiz_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquizjob',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
