# Generated by Django 6.0.7 on 2026-10-08 12:28

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_ai_quiz_job_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquizjob',
            name='plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiquizjob',
            name='rules_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.uploads.ai_quiz_source_path),
        ),
        migrations.AddField(
            model_name='aiquizjob',
            name='rules_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aiquizjob',
            name='rules_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiquizjob',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='aiquizjob',
            name='standard',
            field=models.CharField(blank=True, choices=[('uzbmb', 'Milliy sertifikat (UZBMB)'), ('ielts', 'IELTS Academic'), ('sat', 'Digital SAT')], default='', max_length=10),
        ),
    ]
