# Generated by Django 6.0.7 on 2026-10-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_ai_quiz_job_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquizjob',
            name='exam_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='aiquizjob',
            name='source_text',
            field=models.TextField(blank=True),
        ),
    ]
