# Generated by Django 6.0.7 on 2026-10-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_ai_quiz_job_source_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquizjob',
            name='source_paths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
