# Generated by Django 6.0.8 on 2026-09-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lesson_reminder_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
