# Generated by Django 6.0.7 on 2026-10-07 05:49

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_teacher_default_reminder_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercertificate',
            name='file',
            field=models.FileField(upload_to=apps.core.uploads.certificate_path),
        ),
    ]
