# Generated by Django 6.0.7 on 2026-09-14 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu_percent', models.FloatField()),
                ('memory_percent', models.FloatField()),
                ('memory_used_mb', models.PositiveIntegerField()),
                ('memory_total_mb', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
