# Generated by Django 6.0.7 on 2026-10-07 05:49

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_submission_feedback_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.uploads.homework_task_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=apps.core.uploads.homework_submission_path),
        ),
    ]
