# Generated by Django 6.0.7 on 2026-10-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_alter_assignment_attachment_alter_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='check_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
