# Generated by Django 6.0.7 on 2026-10-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_unstick_ai_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
