# Generated by Django 6.0.8 on 2026-09-14 19:50

import re

from django.db import migrations, models

# Eski erkin matnli `subject`ni yangi qattiq kodlarga o'tkazish — imlo/katta-kichik
# harf farqlariga chidamli bo'lishi uchun regex. Mos kelmasa — 'other'.
_PATTERNS = [
    (re.compile(r'matem|algebra|geometr', re.IGNORECASE), 'math'),
    (re.compile(r'astronom', re.IGNORECASE), 'astronomy'),
    (re.compile(r'fizik', re.IGNORECASE), 'physics'),
    (re.compile(r'kimyo|ximiy', re.IGNORECASE), 'chemistry'),
    (re.compile(r'biolog', re.IGNORECASE), 'biology'),
    (re.compile(r'ekolog', re.IGNORECASE), 'ecology'),
    (re.compile(r'informat|dastur|program|kompyut', re.IGNORECASE), 'computer_science'),
    (re.compile(r'tarix|histor', re.IGNORECASE), 'history'),
    (re.compile(r'geograf', re.IGNORECASE), 'geography'),
    (re.compile(r'huquq', re.IGNORECASE), 'civics'),
    (re.compile(r'iqtisod', re.IGNORECASE), 'economics'),
    (re.compile(r'adabiyot|ona tili|insho', re.IGNORECASE), 'literature'),
    (re.compile(r'musiqa', re.IGNORECASE), 'music'),
    (re.compile(r"tasviriy|rasm chizish|san'at", re.IGNORECASE), 'art'),
    (re.compile(r'jismoniy', re.IGNORECASE), 'physical_education'),
    (re.compile(r'texnologiya|mehnat', re.IGNORECASE), 'technology'),
    (re.compile(r'shaxmat', re.IGNORECASE), 'chess'),
    (re.compile(r'ingliz|english', re.IGNORECASE), 'english'),
    (re.compile(r'rus tili|russian', re.IGNORECASE), 'russian'),
    (re.compile(r'turk', re.IGNORECASE), 'turkish'),
    (re.compile(r'nemis|german', re.IGNORECASE), 'german'),
    (re.compile(r'fransuz|french', re.IGNORECASE), 'french'),
    (re.compile(r'arab', re.IGNORECASE), 'arabic'),
    (re.compile(r'xitoy|chinese', re.IGNORECASE), 'chinese'),
    (re.compile(r'koreys|korean', re.IGNORECASE), 'korean'),
    (re.compile(r'yapon|japan', re.IGNORECASE), 'japanese'),
]


def normalize_subjects(apps, schema_editor):
    Course = apps.get_model('lessons', 'Course')
    for course in Course.objects.all().iterator():
        text = course.subject or ''
        matched = 'other'
        for pattern, code in _PATTERNS:
            if pattern.search(text):
                matched = code
                break
        if course.subject != matched:
            course.subject = matched
            course.save(update_fields=['subject'])


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_lessonreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Matematika'), ('physics', 'Fizika'), ('astronomy', 'Astronomiya'), ('chemistry', 'Kimyo'), ('biology', 'Biologiya'), ('ecology', 'Ekologiya'), ('computer_science', 'Informatika'), ('history', 'Tarix'), ('geography', 'Geografiya'), ('civics', 'Huquq asoslari'), ('economics', 'Iqtisodiyot asoslari'), ('literature', 'Ona tili va adabiyot'), ('music', 'Musiqa'), ('art', "Tasviriy san'at"), ('physical_education', 'Jismoniy tarbiya'), ('technology', 'Texnologiya'), ('chess', 'Shaxmat'), ('english', 'Ingliz tili'), ('russian', 'Rus tili'), ('turkish', 'Turk tili'), ('german', 'Nemis tili'), ('french', 'Fransuz tili'), ('arabic', 'Arab tili'), ('chinese', 'Xitoy tili'), ('korean', 'Koreys tili'), ('japanese', 'Yapon tili'), ('other', 'Boshqa')], default='other', max_length=100),
        ),
        migrations.RunPython(normalize_subjects, migrations.RunPython.noop),
    ]
