# Generated by Django 6.0.7 on 2026-09-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_course_subject_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
