# Generated by Django 6.0.7 on 2026-09-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_alter_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
    ]
