# Generated by Django 6.0.7 on 2026-09-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_remove_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
