# Generated by Django 6.0.8 on 2026-09-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link_id_notification_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
